require:
  - rubocop-rails

AllCops:
  Exclude:
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/setup
    - bin/spring
    - db/schema.rb
    - db/migrate/*
    - lib/tasks/auto_annotate_models.rake
    - .pryrc
    - config/environments/*
    - config/deploy.rb
    - config/initializers/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
Metrics/BlockLength:
  Max: 198
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 20
Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
