version: '3'
volumes:
  mongo_data: {}
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: mongo
    volumes:
      - mongo_data:/var/lib/mongo/data
    ports:
      - 27017:27017
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80