production:
  clients:
    default:
      database: api_core_production
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - db:27017
      options:
  options:
development:
  clients:
    default:
      database: api_core_development
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: api_core_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
